apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-catalog
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: "registry.ng.bluemix.net/<namespace>/catalog:latest"
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
   - protocol: TCP
     port: 8080
     nodePort: 30111
